# Generated by Django 5.1 on 2025-01-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_author_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.AddField(
            model_name='author',
            name='Image',
            field=models.ImageField(null=True, upload_to='Media/auther_Pic'),
        ),
        migrations.AddField(
            model_name='book',
            name='Image',
            field=models.ImageField(null=True, upload_to='Media/book_Pic'),
        ),
    ]
