# Generated by Django 5.1 on 2025-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_remove_author_profile_link_remove_book_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='auther_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
